### ISSUE TITLE
load local data files?

### ISSUE THREAD

**Issue by unhammer** [DougBurke/vega-view#3]
I tried putting "foo.tsv" in the same directory as the vega spec json, with just `foo.tsv`, but I get a 404. How do I load local data? It seems like it tries to parse all files there as json before serving them, and the gives a 404 on a parse error (should be 500?), the returned content from http://localhost:8082/display/foo.tsv is `"Error in $: Failed reading: not a valid json value at 'col1col2col3'"`.

**Comment by DougBurke** [comment]
You would not view the data file (e.g. `foo.tsv`) directly. You view the spec file and it references the file. So if you have

```
% ls -lt examples
total 12
-rw-r--r-- 1 dburke dburke 313 Feb 12 15:21 bar-file.vg.json
-rw-r--r-- 1 dburke dburke  49 Feb 12 15:19 data.csv
-rw-r--r-- 1 dburke dburke 528 Feb 12 15:18 bar.vg.json
```

where I've used the Vega-Lite bar example, namely

```
% cat examples/bar.vg.json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

and then converted it to read in from a file

```
% cat examples/bar-file.vg.json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with loaded data.",
  "data": { "url": "data.csv"},
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

with the data (where the first element is labelled X rather than A so I can easily check they are displaying things correctly)

```
% cat examples/data.csv
a,b
X,28
B,55
C,43
D,91
E,81
F,53
G,19
H,87
I,52
```
 
then viewing the directory should show

![screen1](https://user-images.githubusercontent.com/224638/107819063-8ca9ab00-6d46-11eb-8de2-7aad5a47d1a2.png)

and if you go to either page (either clicking on the name or, as shown here, clicking on the "right arrow") you'll see the plot:

- examples/bar.vg.json

![screen2](https://user-images.githubusercontent.com/224638/107819926-f1b1d080-6d47-11eb-8815-591669a7af16.png)

- examples/bar-file.vg.json

![screen3](https://user-images.githubusercontent.com/224638/107819938-f7a7b180-6d47-11eb-8c19-859f21d5c27f.png)

(you can see my cunning plan for changing the first row, it is now at the end of the plot).

Does this help?

**Comment by unhammer** [comment]
Yeah, it's the bar-file method I was trying to get to work, where I get this:

![bilde](https://user-images.githubusercontent.com/56868/107847650-a3570d00-6ded-11eb-8c4d-0a0fe43a1df0.png)

(that's after putting data.csv in the parent of `examples` – if I put it in `examples`, I just get a 404 with Response payload `"data.csv: openBinaryFile: does not exist (No such file or directory)"`)

**Comment by unhammer** [comment]
Oh, I see https://github.com/DougBurke/vega-view/commit/b54e297dfe16032bf643874412e88d40171f0bae introduced loading local data and an assumption about other files ending in vg.json (maybe put that in ChangeLog.md?). 

`stack install`gave me 0.3.1.6, upgrading to 0.3.1.7 worked :-)  I'll close this then.
